kind: pipeline
type: docker
name: ansible-galaxy-publish

steps:
- name: build
  image: docker.io/geerlingguy/docker-debian11-ansible
  commands:
  - ansible-galaxy collection build

- name: publish
  image: docker.io/geerlingguy/docker-debian11-ansible
  environment:
    ANSIBLE_GALAXY_TOKEN:
      from_secret: ansible_galaxy_token
  commands:
  -  ansible-galaxy collection publish $(find . -type f -name "nightly_brew-ansible_guacamole-*.tar.gz" -printf "%f\n") --token $ANSIBLE_GALAXY_TOKEN

trigger:
  event:
  - tag