name: Build and push artifacts to Ansible Galaxy
run-name: Build and push artifacts to Ansible Galaxy
on: [create]

jobs:
  build_and_push:
    steps:
    - name: install ansible
      run: apt-get update && apt-get install -y --no-install-recommends ansible
    - name: clone repo
      uses: actions/checkout@v4
    - name: build collection
      run: ansible-galaxy collection build
    - name: push to galaxy
      env:
        ANSIBLE_GALAXY_TOKEN: ${{ secrets.ANSIBLEGALAXYTOKEN }}
      run: ansible-galaxy collection publish $(find . -type f -name "nightly_brew-ansible_guacamole-*.tar.gz" -printf "%f\n") --token $ANSIBLE_GALAXY_TOKEN