---

- name: Log into guacamole
  ansible.builtin.uri:
    url: "{{ guacamole_url }}/api/tokens"
    method: "POST"
    validate_certs: false
    body_format: "form-urlencoded"
    body:
    - ['username', '{{ guacamole_username }}']
    - ['password', '{{ guacamole_password }}']
  register: 'guacamole_auth'

- name: Persist login token
  ansible.builtin.set_fact:
    "guacamole_authdata": "{{ guacamole_auth }}"
