---

argument_specs:
  main:
    short_description: "create new guacamole users or update existing ones"
    options:
      guacamole_url:
        description: "The url of the guacamole instance"
        type: "str"
        required: true
      guacamole_authdata:
        description: "Authentication data for guacamole"
        type: "str"
        required: true
      guacamole_users:
        description: "The list of users to create or update"
        type: "list"
        elements: "dict"
        required: true
        options:
          username:
            description: "The name of the user"
            type: "str"
            required: true
          password:
            description: "The user password"
            type: "str"
            required: true
